apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "user-service"
  annotations:
    github.com/project-slug: MSurmach/user-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
